# Change these first
owner: Blue-fin-Software-Solutions # Your GitHub organization or username, where this repository lives
repo: BF-API-UPPTIME # The name of this repository

sites:
  - name: ITS API
    url: https://itsbackofficeapi.azurewebsites.net/swagger/index.html
    icon: https://www.industrytrainingservices.com/wp-content/uploads/2023/07/cropped-ITS-Logo-Main@1x-4.png
  - name: ITS Token Service
    url: https://its-tokenserviceapi.azurewebsites.net/.well-known/openid-configuration
    icon: https://www.industrytrainingservices.com/wp-content/uploads/2023/07/cropped-ITS-Logo-Main@1x-4.png
  - name: ITS Public API
    url: https://its-public-web-api-live.azurewebsites.net/swagger/index.html
    icon: https://www.industrytrainingservices.com/wp-content/uploads/2023/07/cropped-ITS-Logo-Main@1x-4.png
  - name: Express EFDS API
    url: https://webservices.expressfreight.co.uk:10821/swagger/index.html
    icon: https://www.expressfreight.co.uk/imgs/logo.png
  - name: Test Broken Site 1
    url: https://thissitedoesnotexistbf.koj.co
  - name: Test Broken Site 2
    url: https://thissitedoesnotexistbf1.koj.co
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /BF-API-UPPTIME
  logoUrl: https://www.bluefinsoftware.co.uk/wp-content/uploads/2014/01/logo.png
  name: Blue-Fin API Up-Time Monitor 
  favicon: https://www.bluefinsoftware.co.uk/wp-content/uploads/2014/01/favicon.png
  introTitle: "Updates on all Blue-Fin APIs"
  introMessage: Click on each API for more detail
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
